### ISSUE TITLE
Optimize makefile for local docker testing

### ISSUE THREAD

**Issue by joe94** [xmidt-org/scytale#115]
The solution was already accepted in Talaria (https://github.com/xmidt-org/talaria/commit/3db2d63beee9e6ad84295fdfafd5c06e84392b44) and we just need to port it over here

**Comment by ThirumlaDevi** [comment]
@joe94 If I am getting this right, you want to port the local docker image build instruction from [this README section](https://github.com/xmidt-org/scytale#docker) to Makefile. 

On "make local-docker" command
1.  Remove image with tag _**scytale:local**_
2. Then, build new image with tag _**scytale:local**_

**Comment by joe94** [comment]
I want to port over all the changes in the commit diff I provided above. The dockerfile/makefile/readme files across our repos are almost identical so it should be easy to see what needs to be update.
Here's another example: https://github.com/xmidt-org/tr1d1um/commit/bea2f93b075fbd142f757381666996e8e977a9aa

**Comment by ThirumlaDevi** [comment]
Hi @joe94, Can I take this up ?

**Comment by joe94** [comment]
Hey @ThirumlaDevi, so it looks like the team has decided to move forward with testing a slightly different structure for our Makefile and our Dockerfile as part of an effort to simplify them.
**Here they are for your reference:** 
https://github.com/xmidt-org/scytale/blob/main/Dockerfile
https://github.com/xmidt-org/scytale/blob/main/Makefile

Apologies as we should've marked this issue as no longer relevant sooner. I'll go ahead and close this ticket but let us know if you have any other questions! Thanks!
