### ISSUE TITLE
Not able to install scytale-0.1.1-155.el6.x86_64.rpm on CentOS 7.6

### ISSUE THREAD

**Issue by foss-guy** [xmidt-org/scytale#50]
I got this error:

# rpm -Uvh scytale-0.1.1-155.el6.x86_64.rpm 
Preparing...                          ################################# [100%]
	file /usr/bin from install of scytale-0.1.1-155.el6.x86_64 conflicts with file from package filesystem-3.2-25.el7.x86_64

Is there a version of scytale that will get installed on CentOS 7.6? The latest versions of both talaria and tr1d1um got installed viz talaria-0.1.1-244.el6.x86_64.rpm and  tr1d1um-0.1.1-326.el6.x86_64.rpm.

**Comment by foss-guy** [comment]
I noticed later that the rpm names contain el6, so is this even expected to run on CentOS 7.x?

**Comment by schmidtw** [comment]
We haven't had time to debug the various el6 vs el7 differences, so "probably not today".  We would like to move from supervisord to systemd as well.

**Comment by joe94** [comment]
We're currently hosting the latest version of our service rpms in copr https://copr.fedorainfracloud.org/coprs/kspring/XMiDT/package/scytale/

Closing this issue due to age.

**Comment by schmidtw** [comment]
We aren't building and maintaining RPMs directly as part of the xmidt pipeline today.  We have a copr build that builds the latest here for reference:

https://copr.fedorainfracloud.org/coprs/kspring/XMiDT/
