### ISSUE TITLE
JSON handler not working when using json.Marshal

### ISSUE THREAD

**Issue by Equanox** [xmidt-org/scytale#70]
I tried to send a `wrp.SimpleRequestResponse{}` to the /device/send endpoint encoded as JSON. There is a handler registered for header `Content-Type: application/json`. 

**What happened:**
I encoded the message using `json.Marshal()` and was wondering why petasos complaint with 
```
{....."device_id":"","error":"Missing device name header","level":"error",.....}
``` 
When you use `json.Marshal()` it will use the name of the exported members as json key 
```
{...Type:SimpleRequestResponseMessageType Source: Destination:mac:112233445566 ....}
```
When you hit the JSON handler it decodes the message using wrp tags, which are not the same as the exported fields. It would expect a json message like this.
```
{"msg_type":3,"source":"","dest":"mac:112233445566",...}
```

As the decoder generated with `wrp.NewDecoderBytes` doesn't spit out any errors when decoding my message (which is ok as he received valid JSON) , i was wondering why i received a empty wrp message  + empty X-Webpa-Device-Name header when the fanout request hit petasos.

**Solution:**
Three things which can prevent future users from making the same mistake:
1)  Change the header from `application/json` to something more appropriate.
2)  Add json tags to `wrp.SimpleRequestResponse` etc. and change https://github.com/xmidt-org/wrp-go/blob/master/wrp/format.go#L34 to json
3) Use `json.Decode` instead of `wrp.Decode`

I would opt for option 3, but i might miss some arguments why you actually decided to use `wrp.Decode`

**Comment by kcajmagic** [comment]
@Equanox I can't remember why we opted to not add json tags. I'll see if I can find some more information on this. For now the user of scytale should use the `wrp.Encode` method and leverage the `application/msgpack` content type header. 

Another option is to use the wrp payload as body and all the headers in the http for the request. Like this example in [go-parodus](https://github.com/xmidt-org/go-parodus/tree/master/examples/request-response#testing)

**Comment by schmidtw** [comment]
I have reached out to some folks for input.  I think you bring up several good issues @Equanox .  It sounds like we need to add `json` decoders in *wrp-go* so that json.Decode will work as well as wrp.Decode.

Why use `wrp.Decode` vs. `json.Decode()` ? performance - ugorji was faster, there are likely other faster implementations as well.

**Comment by Equanox** [comment]
@schmidtw thx. Ok so adding json tags / json decoders in _wrp-go_ is the way to go. I may provide a pull request. But it'll take some time as this is not top priority right now.

**Comment by kristinaspring** [comment]
@Equanox, I've opened a new issue in the wrp-go package to fix the struct tags.  Is there anything else that needs to be discussed for this issue? Can we close this?
