### ISSUE TITLE
Add functionality for a request to be done on behalf of someone else

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/scytale#77]
In addition to the authorization header, we want to add another header that allows client A to submit a request on behalf of another client, B.  So client A's jwt will be in the authorization header, and the jwt of client B will be in a separate header.  This means that client B may not have access to scytale, while client A does.  Client B's jwt token may provide other context that talaria wants to examine.

related to https://github.com/xmidt-org/scytale/issues/74.  When we start forwarding a jwt to talaria, we want to make sure it's either the one jwt we receive, or it's the jwt from client B in the above scenario.

**Comment by johnabass** [comment]
This is a more general issue than just scytale.  We should probably add a generic way of passing zero or more security tokens that represent an arbitrary chain of security information.  That will futureproof things without adding much work.  This feature belongs in bascule.

**Comment by joe94** [comment]
We have abandoned this approach in favor of leveraging WRP messages as a way to pass these credentials.
